### ISSUE TITLE
how to convert excel file into markdown format?

### ISSUE THREAD

**Issue by samosun** [SpursGoZmy/Tabular-LLM#6]
您好，对于复杂格式的excel文档 ，如果想转换成 markdown格式，有什么好的工具推荐吗？

复杂表格：上述3种表格的表头只分布于表格的左方或者上方，而复杂表格的表头可以分布于表格的任意位置，尤其是表头的右下方区域，并可能与普通数据混合在一起，比如专业设备的文档中可能利用这类表格记录设备的基本信息、政府部门的登记表格、公司的面试申请表等也多为复杂表格。

**Comment by SpursGoZmy** [comment]
1. 可以使用[openpyxl](https://openpyxl-chinese-docs.readthedocs.io/zh-cn/latest/tutorial.html)第三方库读取excel表格。
2. 通过[Worksheet.merged_cells.ranges](https://blog.51cto.com/u_16213447/8903247)识别出所有合并单元格。
3. 按照自定义的方式对所有合并单元格进行处理（因为markdown表格无法表示合并单元格），比如把合并单元格的内容复制多份，而不是只保留左上角的单元格内容。是把合并单元格内容复制多份还是只保留左上角的内容需要自己测试哪种效果更好。
4. 通过[Worksheet.iter_rows方法](https://blog.51cto.com/u_16213447/8903247)遍历每行的单元格内容，按照markdown表格语法构建 markdown格式的表格。注意：markdown表格无法表示合并单元格，想要表示合并单元格只能使用html等格式。

除了openpyxl，也有其他第三方库可选，比如pandas、xlwings，我自己用openpyxl感觉挺方便的。
